## Váriáveis

nomes que vão armazenar valores.

**string** = textos -> entre aspas

**int** = números inteiros (1 ou 2 ou 3) 

**float** = números com casas decimais -> 9.3456, 5.06

**booleanas** = True ou False (verdadeiro ou falso) 

nomes que sejam em letras minusculas, facil de entender, NUNCA começam com números.

## Constantes
PI = 3.1415

G_FORCE = 9.8

In [77]:
a = 12
print(a)

12

In [78]:
PI = 3.1415 ## float
G_FORCE = 9.8 ## float
NOME = "Sthefanie" ## String
NUM_CASA = 2 ## inteiro
print(PI)
print(G_FORCE)
print(NOME)
print(NUM_CASA)

3.1415
9.8
Sthefanie
2

In [79]:
nome = "Samuel"
idade = 10
estudante = True
nota_biologia = 9.5

In [80]:
print(nome)
print(idade)
print(estudante)
print(nota_biologia)

Samuel
10
True
9.5

In [81]:
print(type(idade))

<class 'int'>

In [82]:
print(idade+1)

11

In [83]:
print(type(nome))
print(type(estudante))
print(type(nota_biologia))

<class 'str'>
<class 'bool'>
<class 'float'>

In [84]:
# aniversario
dia = "30" # string, mas deveria ser inteiro
mes = "novembro" # string, pode ser feito uma modificação para inteiro (mes 11)
ano = "1998" # string mas precisa ser inteiro para fazer calculos de idade

In [85]:
print(dia,mes,ano)

30 novembro 1998

In [86]:
print(type(dia))
print(type(mes))
print(type(ano))

<class 'str'>
<class 'str'>
<class 'str'>

In [87]:
type(ano)

str

In [88]:
ano = int(ano)
type(ano)

int

In [89]:
ano

1998

In [90]:
idade = 2030 - ano
idade

32

In [91]:
nota_biologia = int(nota_biologia)

In [92]:
nota_biologia

9

## Conversões das variáveis

`nome_variavel = int(nome_variavel)` = de string para int, de float para int

`nome_variavel = str(nome_variavel)`

`nome_variavel = float(nome_variavel)`

`nome_variavel = bool(nome_variavel)`

# Operadores 
## Operadores matemáticos (int e float)

soma + -> somando valores

subtração - -> subtraçao de valores

divisão / 

multiplicação * 

potência ** -> elevar um valor à outro 

módulo % -> é o resto da divisão 

## Operadores relacionais 
Eles sempre retornam um resultado em bool (True ou False)

`>` maior que 
`<` menor que 
`>=` maior que ou igual
`<=` menor que ou igual
`==` comparação 
`!=` diferente de

In [93]:
# matematica

a = 10
b = 3
c = 2

soma = a + b + c
subt = a - b - c
mult = a * b * c
div1 = a / b
div2 = a / c
potencia = a ** c
modulo1 = a % b
modulo2 = a % c

In [94]:
print(soma,subt,mult,div1,div2,potencia,modulo1,modulo2)

15 5 60 3.3333333333333335 5.0 100 1 0

In [95]:
teste = div1 * div2
teste

16.666666666666668

In [96]:
print(a != b)

True

## Condicionais e operadores lógicos 

- Sempre vai ter um retorno booleano.
- `if`, `else`, `elif` = se e se não

In [97]:
meta = 300
venda = 350

print(meta <= venda)

True

estrutura if else

if CONDIÇÕES:
    se ela for verdadeira, executa o que está aqui dentro
    se for falso, segue para a próxima
elif CONDIÇÕES:
    se ela for verdadeira, executa o que está aqui dentro
    se for falso, segue para a próxima
else:
    se nenhuma das alternativas acima forem verdadeiras, execute o else.

In [98]:
meta = 300
venda = 250

if venda >= meta:
    print("Meta batida")
else:
    print("Meta não batida")

Meta não batida

In [99]:
venda = 189

if venda >= 300:
    print("Meta batida")
elif venda >= 200:
    print("Faltou pouco para bater a meta!")
elif venda >= 100:
    if venda > 190:
        print("Você quase chegou nos 200, vamos tentar novamente amanha!")
    else:
        print("Faltou muito para bater a meta!")
else:
    print("Meta não batida")

Faltou muito para bater a meta!

Operadores lógicos:

`and` = as duas condições precisam ser verdadeiras

`or` = uma das duas condições precisa ser verdadeira

`not` = negação da condição (se a minha condição tiver um resultado verdadeiro, eu vou trocar esse resultado automaticamente para falso)

In [100]:
venda = 689

if venda > 500 or venda < 50:
    print("hoje é um dia atipico")
else:
    print("Hoje é um dia normal")

hoje é um dia atipico

In [101]:
## dias normais e dias de feriados
flag = "feriado"
venda = 9

if flag =="feriado":
    if venda > 500:
        print("hoje é um dia de feriado, faz sentido nossa venda.")
    elif venda < 50:
        print("hoje é um dia de feriado, mas nossa venda foi muito baixa.")
    else:
        print("Hoje é um dia normal")
else: 
    if venda > 500 or venda < 50:
        print("o que pode ter acontecido de diferente?")
    else:
        print("Hoje é um dia de vendas normais")

hoje é um dia de feriado, mas nossa venda foi muito baixa.

## Listas e tuplas

listas são mutaveis e as tuplas não são

lista  = `[]`
tupla = `()`

In [102]:
frutas = ["banana", "maçã", "laranja", "abacaxi", "melancia"]
frutas_vermelhas = ('amora', 'framboesa', 'morango', 'cereja')

In [103]:
print(frutas)

['banana', 'maçã', 'laranja', 'abacaxi', 'melancia']

In [104]:
print(frutas_vermelhas)

('amora', 'framboesa', 'morango', 'cereja')

In [105]:
frutas.append("kiwi") ## add um elemento no final da lista
print(frutas)

['banana', 'maçã', 'laranja', 'abacaxi', 'melancia', 'kiwi']

In [106]:
frutas.extend(frutas_vermelhas) ## add uma lista no final da lista
print(frutas)

['banana', 'maçã', 'laranja', 'abacaxi', 'melancia', 'kiwi', 'amora', 'framboesa', 'morango', 'cereja']

In [107]:
frutas.remove("banana") ## remove um elemento da lista
print(frutas)

['maçã', 'laranja', 'abacaxi', 'melancia', 'kiwi', 'amora', 'framboesa', 'morango', 'cereja']

In [108]:
frutas.pop() ## remove o ultimo elemento da lista
print(frutas)

['maçã', 'laranja', 'abacaxi', 'melancia', 'kiwi', 'amora', 'framboesa', 'morango']

## indices e fatias

tudo começa em 0 se estivermos contando da esquerda para a direita
0, 1, 2, 3 ...
0 = primeiro item
1 = segundo item
2 = terceiro item
...

se estamos contando do último item até o primeiro (da direita para a esquerda)
-1, -2, -3, -4 ...
-1 = último item
-2 = penúltimo item
-3 = antepenúltimo item 
...

In [109]:
frutas.pop(-2)
print(frutas)

['maçã', 'laranja', 'abacaxi', 'melancia', 'kiwi', 'amora', 'morango']

In [110]:
frutas = ["banana", "maçã", "laranja", "abacaxi", "melancia", 'amora', 'cereja', 'framboesa', 'morango', 'uva']
frutas

['banana',
 'maçã',
 'laranja',
 'abacaxi',
 'melancia',
 'amora',
 'cereja',
 'framboesa',
 'morango',
 'uva']

In [111]:
frutas[-1] # [] é como se fosse uma barra de pesquisa

'uva'

In [112]:
frutas[9]

'uva'

In [113]:
frutas_vermelhas = frutas[5:9] ## fatiamento de lista
## no fatiamento o primeiro numero é o indice inicial e o 
# #segundo numero é o indice final, mas ele não inclui o elemento 
# do indice final, ou seja, ele vai até o elemento anterior ao 
# indice final.
frutas_vermelhas

['amora', 'cereja', 'framboesa', 'morango']

In [114]:
frutas_vermelhas = frutas[:4] ## fatiamento de lista
frutas_vermelhas

['banana', 'maçã', 'laranja', 'abacaxi']

In [115]:
frutas.sort() #organiza de forma alfabetica a lista
frutas

['abacaxi',
 'amora',
 'banana',
 'cereja',
 'framboesa',
 'laranja',
 'maçã',
 'melancia',
 'morango',
 'uva']

In [116]:
frutas.reverse() #organiza de forma alfabetica a lista, mas de forma reversa
frutas

['uva',
 'morango',
 'melancia',
 'maçã',
 'laranja',
 'framboesa',
 'cereja',
 'banana',
 'amora',
 'abacaxi']

In [117]:
frutas.sort(reverse=True) #organiza de forma alfabetica a lista, mas de forma decrescente
frutas

['uva',
 'morango',
 'melancia',
 'maçã',
 'laranja',
 'framboesa',
 'cereja',
 'banana',
 'amora',
 'abacaxi']

In [118]:
lista_listas= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lista_listas

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [119]:
lista_listas[-1].append(10) ## add um elemento no final da lista

In [120]:
lista_listas

[[1, 2, 3], [4, 5, 6], [7, 8, 9, 10]]

In [121]:
lista_listas.append(11)

In [122]:
lista_listas

[[1, 2, 3], [4, 5, 6], [7, 8, 9, 10], 11]

In [123]:
lista_listas[3]

11

In [124]:
meta = 150
vendas = [95, 200, 67, 146, 250, 297, 386]

In [125]:
if vendas[1] < meta:
    print("Meta não batida")
else:
    print("Meta batida")

Meta batida

## Laço de repetição FOR

- ele percorre a lista toda, um dataset, excel
  
- Qual ação eu quero que seja repetida até o final dos meus dados?

```
for fruta in salada_de_frutas:

```

for ... in ... :

```
for item in lista:
    faça algo 

```

In [126]:
vendas = [95, 200, 67, 146, 250, 297, 386]

for item in vendas:
    # item vai assumir a forma de: 
    # vendas[0], vendas[1],vendas[2], vendas[3], vendas[4], vendas[5], vendas[6]
    print(item)
    print('---')

95
---
200
---
67
---
146
---
250
---
297
---
386
---

In [127]:
meta = 150
vendas = [95, 200, 67, 146, 250, 297, 386]

for venda in vendas:
    if venda < meta:
        print("Meta não batida")
    else:
        print("Meta batida")

Meta não batida
Meta batida
Meta não batida
Meta não batida
Meta batida
Meta batida
Meta batida

## Laço de repetição - WHILE
- ele vai repetir até que a condição dada seja falsa
- qual a condiçao de parada?

```
while condição :

```

In [128]:
meta = 150
vendas = [95, 200, 67, 146, 250, 297, 386]

In [129]:
for venda in vendas:
    print(venda)

95
200
67
146
250
297
386

In [130]:
len(vendas)

7

In [131]:
# aqui vamos usar um iterador

i = 0

while i < len(vendas):
    print(vendas[i])
    i += 1 # i = i + 1

95
200
67
146
250
297
386

In [132]:
meta_semanal = 800
vendas = [95, 200, 67, 146, 250, 297, 386]

In [133]:
dia = 0
acumulado = 0

while acumulado < meta_semanal and dia < len(vendas): 
    acumulado += vendas[dia]
    print(dia) 
    dia += 1
    
    print(acumulado)
    print('---')

0
95
---
1
295
---
2
362
---
3
508
---
4
758
---
5
1055
---

## Dicionários 

usa as {} para definir um dicionário

`{'chave': valor}`

`.values()` - percorre somente os valores

`.items()` - percorre os pares

In [134]:
vendas = [95, 200, 67, 146, 250, 297, 386]
dias_semana = ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado', 'domingo']

In [135]:
# quero a venda de quarta-feira
vendas[2] # 2 é o índice que fala que é quarta-feira

67

In [136]:
vendas_semana = {
    'segunda': 95,
    'terça': 200,
    'quarta': 67,
    'quinta': 146,
    'sexta': 250,
    'sábado': 297
}

In [137]:
# vendas_semana['domingo']

In [138]:
vendas_semana['domingo'] = 300

In [139]:
print(vendas_semana)

{'segunda': 95, 'terça': 200, 'quarta': 67, 'quinta': 146, 'sexta': 250, 'sábado': 297, 'domingo': 300}

In [140]:
vendas_semana['domingo']

300

In [141]:
vendas_semana['domingo'] = 30
vendas_semana

{'segunda': 95,
 'terça': 200,
 'quarta': 67,
 'quinta': 146,
 'sexta': 250,
 'sábado': 297,
 'domingo': 30}

In [142]:
for venda in vendas_semana:
    print(venda)

segunda
terça
quarta
quinta
sexta
sábado
domingo

In [143]:
for venda in vendas_semana.values():
    print(venda)

95
200
67
146
250
297
30

In [144]:
for venda in vendas_semana.items():
    print(venda)

('segunda', 95)
('terça', 200)
('quarta', 67)
('quinta', 146)
('sexta', 250)
('sábado', 297)
('domingo', 30)

In [145]:
meta = 150

for venda in vendas_semana.values():
    if venda < meta:
        print("Meta não batida")
    else:
        print("Meta batida")

Meta não batida
Meta batida
Meta não batida
Meta não batida
Meta batida
Meta batida
Meta não batida

In [146]:
produtos_vendidos = ['barra', 'barra', 'barra', 'bombom', 'bombom', 'chocolate quente']

contagem_produtos = {}

for produto in produtos_vendidos:
    if produto in contagem_produtos: 
        contagem_produtos[produto] += 1
    else:
        contagem_produtos[produto] = 1

print(contagem_produtos)

{'barra': 3, 'bombom': 2, 'chocolate quente': 1}

In [147]:
## método .get()

produtos_vendidos = ['barra', 'barra', 'barra', 'bombom', 'bombom', 'chocolate quente']
contagem = {}

for produto in produtos_vendidos:
    contagem[produto] = contagem.get(produto, 0) + 1

In [148]:
contagem

{'barra': 3, 'bombom': 2, 'chocolate quente': 1}

## Sets e valores que são únicos
`set()` é uma função que retorna valores ÚNICOS. Ele não tem índices nem ordens. 

Nós podemos utilizar os sets quando a pergunta não é a quantidade de venda que foi feita, mas sim quais os produtos únicos que foram vendidos.

No caso anterior, era a barra de chocolate, o bombom e o chocolate quente - esses 3 produtos.

In [149]:
produtos_unicos = set(produtos_vendidos) ## guarda cada produto uma única vez
print(produtos_unicos)

{'bombom', 'barra', 'chocolate quente'}

In [150]:
len(produtos_unicos) ## quantos produtos diferentes foram vendidos

3

In [151]:
vendas_semana1 = {'segunda': 95,
 'terça': 200,
 'quarta': 67,
 'quinta': 146,
 'sexta': 250,
 'sábado': 297,
 'domingo': 30}

vendas_semana2 = {'segunda': 140,
 'terça': 197,
 'quarta': 207,
 'quinta': 360,
 'sexta': 250,
 'sábado': 280,
 'domingo': 0}

In [152]:
print(vendas_semana1)
print(vendas_semana2)

{'segunda': 95, 'terça': 200, 'quarta': 67, 'quinta': 146, 'sexta': 250, 'sábado': 297, 'domingo': 30}
{'segunda': 140, 'terça': 197, 'quarta': 207, 'quinta': 360, 'sexta': 250, 'sábado': 280, 'domingo': 0}

In [153]:
total_semana = 0
for venda in vendas_semana1.values():
    total_semana += venda
print(total_semana)

1085

In [154]:
total_semana = 0
for venda in vendas_semana2.values():
    total_semana += venda
print(total_semana)

1434

Como criar uma função:

```
def nome_funcao(parametros):
    comandos
```

In [155]:
def boas_vindas():
    print("Boas vindas ao nosso mundo de Python!")

In [156]:
boas_vindas()

Boas vindas ao nosso mundo de Python!

In [157]:
nome = 'Sthefanie'
print(f"Boas vindas, {nome}, ao nosso mundo de Python!")

Boas vindas, Sthefanie, ao nosso mundo de Python!

In [158]:
def boas_vindas(nome):
    print(f"Boas vindas, {nome}, ao nosso mundo de Python!") # f = format

In [159]:
boas_vindas('Monica')

Boas vindas, Monica, ao nosso mundo de Python!

In [160]:
def soma_total(vendas): #o valor vendas precisa ser, nesse caso, um dicionário
    valor_total_semana = 0
    for venda in vendas.values():
        valor_total_semana += venda
    print(valor_total_semana)

In [161]:
soma_total(vendas_semana1)

1085

In [162]:
soma_total(vendas_semana2)

1434

In [163]:
total_semana

1434

### variáeis locais e globais - com funções

In [164]:
nome = 'Sthefanie' # variável global

def saudacao(nome_completo):
    aula = 'funções' # variável local
    print(f'Boas vindas a nossa aula de Python, de {aula}, {nome_completo} ou posso te chamar somente de {nome}?')

In [165]:
saudacao('Sthefanie Monica')

Boas vindas a nossa aula de Python, de funções, Sthefanie Monica ou posso te chamar somente de Sthefanie?

### como fazer uma função retornar uma variável para ser global?

In [166]:
def soma_total_print(vendas): #o valor vendas precisa ser, nesse caso, um dicionário
    valor_total_semana = 0
    for venda in vendas.values():
        valor_total_semana += venda
    print(valor_total_semana)

In [167]:
def soma_total_return(vendas): #o valor vendas precisa ser, nesse caso, um dicionário
    valor_total_semana = 0
    for venda in vendas.values():
        valor_total_semana += venda
    return valor_total_semana

In [168]:
soma_semana1 = soma_total(vendas_semana1)
soma_semana1

1085

In [169]:
soma_semana1

In [170]:
## como fazer a soma sem criar uma função do 0

print(sum(vendas_semana1.values()))

1085

## Try-except

In [171]:
try:
    arquivo = open("arquivos_importantes/teste2.txt")
    print("Arquivo aberto!")
except:
    print("Não foi possível acessar o arquivo")

Não foi possível acessar o arquivo

# Raise

In [ ]:
numero = input("Digite um número: ") #input é uma função onde voce insere um valor AO VIVO
numero = int(numero)

if numero == 0:
    raise Exception("O número deve ser diferente de zero")

print(1000 / numero)

In [ ]:
# arquivo nomes_ruins.py
a = 25
b = 4
c = a * b

def f(x):
    return x * 0.9

In [ ]:
f(c)

90.0

In [ ]:
# arquivo nomes_bons.py
preco_unitario = 25
quantidade = 4
preco_total = preco_unitario * quantidade

def aplicar_desconto(valor):
    '''
    Função que aplica desconto de 10% no valor da compra. 
    Válida somente para produtos próximos da validade, com selo vermelho.
    '''
    return valor * 0.9

In [ ]:
aplicar_desconto(preco_total)

90.0

## Tipos de arquivos: 

.txt 

.csv

.json

In [ ]:
# arquivo abrir_arquivo.py
with open("arquivos_importantes/teste.txt", "r", encoding="utf-8") as arquivo:
    conteudo = arquivo.read()
    print(conteudo)

Eu estou aprendo alemão.

Lista de compras:
- tomate
- cebola
- pipoca
- suco de laranja

In [ ]:
with open("arquivos_importantes/teste.txt", "r", encoding="utf-8") as arquivo:
    for linha in arquivo:
        print(linha.strip())

Eu estou aprendo alemão.

Lista de compras:
- tomate
- cebola
- pipoca
- suco de laranja

In [ ]:
# arquivo escrever_txt.py
with open("arquivos_importantes/compras.txt", "w", encoding="utf-8") as arquivo:
    arquivo.write("arroz\n")
    arquivo.write("feijão\n")

In [ ]:
# arquivo escrever_txt.py
with open("arquivos_importantes/teste.txt", "w", encoding="utf-8") as arquivo:
    arquivo.write("arroz\n")
    arquivo.write("feijão\n")

In [ ]:
# arquivo abrir_arquivo.py
with open("arquivos_importantes/teste.txt", "r", encoding="utf-8") as arquivo:
    conteudo = arquivo.read()
    print(conteudo)

arroz
feijão

In [ ]:
with open("arquivos_importantes/teste.txt", "a", encoding="utf-8") as arquivo:
    arquivo.write("frango\n")

In [ ]:
# arquivo abrir_arquivo.py
with open("arquivos_importantes/teste.txt", "r", encoding="utf-8") as arquivo:
    conteudo = arquivo.read()
    print(conteudo)

arroz
feijão
frango

In [ ]:
# arquivo ler_csv.py
import csv

with open("arquivos_importantes/pessoas.csv", "r", encoding="utf-8") as arquivo:
    leitor = csv.DictReader(arquivo, delimiter=";")
    for linha in leitor:
        print(f"{linha['nome']} tem {linha['idade']} anos")

Ana tem 28 anos
Bruno tem 35 anos
Carla tem 22 anos
Diego tem 41 anos
Eduarda tem 19 anos
Felipe tem 30 anos
Gabriela tem 26 anos
Henrique tem 52 anos

In [ ]:
pessoas = [
    {"nome": "Ana", "idade": 28, "cidade": "Curitiba"},
    {"nome": "Bruno", "idade": 35, "cidade": "Ponta Grossa"},
]

In [ ]:
with open("arquivos_importantes/pessoas.csv", "w", encoding="utf-8", newline="") as arquivo:
    escritor = csv.DictWriter(arquivo, fieldnames=["nome", "idade", "cidade"])
    escritor.writeheader()
    escritor.writerows(pessoas)

In [ ]:
# arquivo ler_json.py
import json

with open("arquivos_importantes/aluna.json", "r", encoding="utf-8") as arquivo:
    dados = json.load(arquivo)

In [ ]:
print(dados["nome"])
print(dados["cursos"][2])

Sthefanie
Machine Learning

In [ ]:

aluna = {
    "nome": "Ana",
    "idade": 28,
    "cursos": ["Python", "SQL"]
}

In [ ]:
with open("arquivos_importantes/aluna2.json", "w", encoding="utf-8") as arquivo:
    json.dump(aluna, arquivo, indent=4, ensure_ascii=False)

In [ ]:
with open("arquivos_importantes/aluna2.json", "r", encoding="utf-8") as arquivo:
    aluna = json.load(arquivo)

In [ ]:
aluna["idade"] = 29
aluna["cursos"].append("Pandas")

In [ ]:
with open("arquivos_importantes/aluna2.json", "w", encoding="utf-8") as arquivo:
    json.dump(aluna, arquivo, indent=4, ensure_ascii=False)

## O que são APIs e como usa-las?

In [1]:
import requests

resposta = requests.get("https://pokeapi.co/api/v2/pokemon/pikachu")
print(resposta.status_code)

200

In [2]:
resposta

In [5]:
dados = resposta.json()
print(dados["name"])

pikachu

In [6]:
dados

{'id': 25,
 'name': 'pikachu',
 'base_experience': 112,
 'height': 4,
 'is_default': True,
 'order': 35,
 'weight': 60,
 'abilities': [{'is_hidden': False,
   'slot': 1,
   'ability': {'name': 'static',
    'url': 'https://pokeapi.co/api/v2/ability/9/'}},
  {'is_hidden': True,
   'slot': 3,
   'ability': {'name': 'lightning-rod',
    'url': 'https://pokeapi.co/api/v2/ability/31/'}}],
 'past_abilities': [{'generation': {'name': 'generation-iv',
    'url': 'https://pokeapi.co/api/v2/generation/4/'},
   'abilities': [{'is_hidden': True, 'slot': 3, 'ability': None}]}],
 'forms': [{'name': 'pikachu',
   'url': 'https://pokeapi.co/api/v2/pokemon-form/25/'}],
 'game_indices': [{'game_index': 84,
   'version': {'name': 'red', 'url': 'https://pokeapi.co/api/v2/version/1/'}},
  {'game_index': 84,
   'version': {'name': 'blue', 'url': 'https://pokeapi.co/api/v2/version/2/'}},
  {'game_index': 84,
   'version': {'name': 'yellow',
    'url': 'https://pokeapi.co/api/v2/version/3/'}},
  {'game_index': 25,
   'version': {'name': 'gold', 'url': 'https://pokeapi.co/api/v2/version/4/'}},
  {'game_index': 25,
   'version': {'name': 'silver',
    'url': 'https://pokeapi.co/api/v2/version/5/'}},
  {'game_index': 25,
   'version': {'name': 'crystal',
    'url': 'https://pokeapi.co/api/v2/version/6/'}},
  {'game_index': 25,
   'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}},
  {'game_index': 25,
   'version': {'name': 'sapphire',
    'url': 'https://pokeapi.co/api/v2/version/8/'}},
  {'game_index': 25,
   'version': {'name': 'emerald',
    'url': 'https://pokeapi.co/api/v2/version/9/'}},
  {'game_index': 25,
   'version': {'name': 'firered',
    'url': 'https://pokeapi.co/api/v2/version/10/'}},
  {'game_index': 25,
   'version': {'name': 'leafgreen',
    'url': 'https://pokeapi.co/api/v2/version/11/'}},
  {'game_index': 25,
   'version': {'name': 'diamond',
    'url': 'https://pokeapi.co/api/v2/version/12/'}},
  {'game_index': 25,
   'version': {'name': 'pearl',
    'url': 'https://pokeapi.co/api/v2/version/13/'}},
  {'game_index': 25,
   'version': {'name': 'platinum',
    'url': 'https://pokeapi.co/api/v2/version/14/'}},
  {'game_index': 25,
   'version': {'name': 'heartgold',
    'url': 'https://pokeapi.co/api/v2/version/15/'}},
  {'game_index': 25,
   'version': {'name': 'soulsilver',
    'url': 'https://pokeapi.co/api/v2/version/16/'}},
  {'game_index': 25,
   'version': {'name': 'black',
    'url': 'https://pokeapi.co/api/v2/version/17/'}},
  {'game_index': 25,
   'version': {'name': 'white',
    'url': 'https://pokeapi.co/api/v2/version/18/'}},
  {'game_index': 25,
   'version': {'name': 'black-2',
    'url': 'https://pokeapi.co/api/v2/version/21/'}},
  {'game_index': 25,
   'version': {'name': 'white-2',
    'url': 'https://pokeapi.co/api/v2/version/22/'}},
  {'game_index': 25,
   'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}},
  {'game_index': 25,
   'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}},
  {'game_index': 25,
   'version': {'name': 'omega-ruby',
    'url': 'https://pokeapi.co/api/v2/version/25/'}},
  {'game_index': 25,
   'version': {'name': 'alpha-sapphire',
    'url': 'https://pokeapi.co/api/v2/version/26/'}},
  {'game_index': 25,
   'version': {'name': 'sun', 'url': 'https://pokeapi.co/api/v2/version/27/'}},
  {'game_index': 25,
   'version': {'name': 'moon',
    'url': 'https://pokeapi.co/api/v2/version/28/'}},
  {'game_index': 25,
   'version': {'name': 'ultra-sun',
    'url': 'https://pokeapi.co/api/v2/version/29/'}},
  {'game_index': 25,
   'version': {'name': 'ultra-moon',
    'url': 'https://pokeapi.co/api/v2/version/30/'}},
  {'game_index': 25,
   'version': {'name': 'lets-go-pikachu',
    'url': 'https://pokeapi.co/api/v2/version/31/'}},
  {'game_index': 25,
   'version': {'name': 'lets-go-eevee',
    'url': 'https://pokeapi.co/api/v2/version/32/'}},
  {'game_index': 25,
   'version': {'name': 'sword',
    'url': 'https://pokeapi.co/api/v2/version/33/'}},
  {'game_index': 25,
   'version': {'name': 'shield',
    'url': 'https://pokeapi.co/api/v2/version/34/'}},
  {'game_index': 25,
   'version': {'name': 'the-isle-of-armor-sword',
    'url': 'https://pokeapi.co/api/v2/version/35/'}},
  {'game_index': 25,
   'version': {'name': 'the-crown-tundra-sword',
    'url': 'https://pokeapi.co/api/v2/version/36/'}},
  {'game_index': 25,
   'version': {'name': 'brilliant-diamond',
    'url': 'https://pokeapi.co/api/v2/version/37/'}},
  {'game_index': 25,
   'version': {'name': 'shining-pearl',
    'url': 'https://pokeapi.co/api/v2/version/38/'}},
  {'game_index': 25,
   'version': {'name': 'legends-arceus',
    'url': 'https://pokeapi.co/api/v2/version/39/'}},
  {'game_index': 25,
   'version': {'name': 'scarlet',
    'url': 'https://pokeapi.co/api/v2/version/40/'}},
  {'game_index': 25,
   'version': {'name': 'violet',
    'url': 'https://pokeapi.co/api/v2/version/41/'}},
  {'game_index': 25,
   'version': {'name': 'the-teal-mask-scarlet',
    'url': 'https://pokeapi.co/api/v2/version/42/'}},
  {'game_index': 25,
   'version': {'name': 'the-indigo-disk-scarlet',
    'url': 'https://pokeapi.co/api/v2/version/43/'}},
  {'game_index': 84,
   'version': {'name': 'red-japan',
    'url': 'https://pokeapi.co/api/v2/version/44/'}},
  {'game_index': 84,
   'version': {'name': 'green-japan',
    'url': 'https://pokeapi.co/api/v2/version/45/'}},
  {'game_index': 84,
   'version': {'name': 'blue-japan',
    'url': 'https://pokeapi.co/api/v2/version/46/'}},
  {'game_index': 25,
   'version': {'name': 'legends-za',
    'url': 'https://pokeapi.co/api/v2/version/47/'}},
  {'game_index': 25,
   'version': {'name': 'mega-dimension',
    'url': 'https://pokeapi.co/api/v2/version/48/'}}],
 'held_items': [{'item': {'name': 'oran-berry',
    'url': 'https://pokeapi.co/api/v2/item/132/'},
   'version_details': [{'rarity': 50,
     'version': {'name': 'ruby',
      'url': 'https://pokeapi.co/api/v2/version/7/'}},
    {'rarity': 50,
     'version': {'name': 'sapphire',
      'url': 'https://pokeapi.co/api/v2/version/8/'}},
    {'rarity': 50,
     'version': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version/9/'}},
    {'rarity': 50,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rarity': 50,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rarity': 50,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}},
    {'rarity': 50,
     'version': {'name': 'heartgold',
      'url': 'https://pokeapi.co/api/v2/version/15/'}},
    {'rarity': 50,
     'version': {'name': 'soulsilver',
      'url': 'https://pokeapi.co/api/v2/version/16/'}},
    {'rarity': 50,
     'version': {'name': 'black',
      'url': 'https://pokeapi.co/api/v2/version/17/'}},
    {'rarity': 50,
     'version': {'name': 'white',
      'url': 'https://pokeapi.co/api/v2/version/18/'}}]},
  {'item': {'name': 'light-ball',
    'url': 'https://pokeapi.co/api/v2/item/213/'},
   'version_details': [{'rarity': 5,
     'version': {'name': 'ruby',
      'url': 'https://pokeapi.co/api/v2/version/7/'}},
    {'rarity': 5,
     'version': {'name': 'sapphire',
      'url': 'https://pokeapi.co/api/v2/version/8/'}},
    {'rarity': 5,
     'version': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version/9/'}},
    {'rarity': 5,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rarity': 5,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rarity': 5,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}},
    {'rarity': 5,
     'version': {'name': 'heartgold',
      'url': 'https://pokeapi.co/api/v2/version/15/'}},
    {'rarity': 5,
     'version': {'name': 'soulsilver',
      'url': 'https://pokeapi.co/api/v2/version/16/'}},
    {'rarity': 1,
     'version': {'name': 'black',
      'url': 'https://pokeapi.co/api/v2/version/17/'}},
    {'rarity': 1,
     'version': {'name': 'white',
      'url': 'https://pokeapi.co/api/v2/version/18/'}},
    {'rarity': 5,
     'version': {'name': 'black-2',
      'url': 'https://pokeapi.co/api/v2/version/21/'}},
    {'rarity': 5,
     'version': {'name': 'white-2',
      'url': 'https://pokeapi.co/api/v2/version/22/'}},
    {'rarity': 5,
     'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}},
    {'rarity': 5,
     'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}},
    {'rarity': 5,
     'version': {'name': 'omega-ruby',
      'url': 'https://pokeapi.co/api/v2/version/25/'}},
    {'rarity': 5,
     'version': {'name': 'alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version/26/'}},
    {'rarity': 5,
     'version': {'name': 'sun',
      'url': 'https://pokeapi.co/api/v2/version/27/'}},
    {'rarity': 5,
     'version': {'name': 'moon',
      'url': 'https://pokeapi.co/api/v2/version/28/'}},
    {'rarity': 5,
     'version': {'name': 'ultra-sun',
      'url': 'https://pokeapi.co/api/v2/version/29/'}},
    {'rarity': 5,
     'version': {'name': 'ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version/30/'}}]}],
 'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/25/encounters',
 'moves': [{'move': {'name': 'mega-punch',
    'url': 'https://pokeapi.co/api/v2/move/5/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'red-green-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/28/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'blue-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/29/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None}]},
  {'move': {'name': 'pay-day', 'url': 'https://pokeapi.co/api/v2/move/6/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'red-green-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/28/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'blue-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/29/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None}]},
  {'move': {'name': 'thunder-punch',
    'url': 'https://pokeapi.co/api/v2/move/9/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'scarlet-violet',
      'url': 'https://pokeapi.co/api/v2/version-group/25/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'champions',
      'url': 'https://pokeapi.co/api/v2/version-group/32/'},
     'move_learn_method': {'name': 'train',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/12/'},
     'order': None}]},
  {'move': {'name': 'slam', 'url': 'https://pokeapi.co/api/v2/move/21/'},
   'version_group_details': [{'level_learned_at': 20,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'ruby-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/5/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 21,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 21,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 21,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 26,
     'version_group': {'name': 'black-white',
      'url': 'https://pokeapi.co/api/v2/version-group/11/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'colosseum',
      'url': 'https://pokeapi.co/api/v2/version-group/12/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 20,
     'version_group': {'name': 'xd',
      'url': 'https://pokeapi.co/api/v2/version-group/13/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 26,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 26,
     'version_group': {'name': 'x-y',

In [7]:
print(dados["id"])
print(dados["weight"])

25
60

In [8]:
for item in dados["types"]:
    print(item["type"]["name"])

electric

In [9]:
imagem = dados["sprites"]["front_default"]
print(imagem)

https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png

In [14]:
resposta = requests.get("https://pokeapi.co/api/v2/pokemon/panqueca")
if resposta.status_code == 200:
    dados = resposta.json()
    print(dados["name"])
else:
    print("Pokemon não encontrado")

Pokemon não encontrado

In [15]:
resposta = requests.get("https://pokeapi.co/api/v2/pokemon/eevee")
if resposta.status_code == 200:
    dados = resposta.json()
    print(dados["name"])
else:
    print("Pokemon não encontrado")

eevee

In [17]:
resposta = requests.get("https://pokeapi.co/api/v2/pokemon?limit=5&offset=0")
dados = resposta.json()
print(dados)

{'count': 1351, 'next': 'https://pokeapi.co/api/v2/pokemon?offset=5&limit=5', 'previous': None, 'results': [{'name': 'bulbasaur', 'url': 'https://pokeapi.co/api/v2/pokemon/1/'}, {'name': 'ivysaur', 'url': 'https://pokeapi.co/api/v2/pokemon/2/'}, {'name': 'venusaur', 'url': 'https://pokeapi.co/api/v2/pokemon/3/'}, {'name': 'charmander', 'url': 'https://pokeapi.co/api/v2/pokemon/4/'}, {'name': 'charmeleon', 'url': 'https://pokeapi.co/api/v2/pokemon/5/'}]}

In [18]:
parametros = {"limit": 5, "offset": 0}
resposta = requests.get("https://pokeapi.co/api/v2/pokemon", params=parametros)
dados = resposta.json()
dados

{'count': 1351,
 'next': 'https://pokeapi.co/api/v2/pokemon?offset=5&limit=5',
 'previous': None,
 'results': [{'name': 'bulbasaur',
   'url': 'https://pokeapi.co/api/v2/pokemon/1/'},
  {'name': 'ivysaur', 'url': 'https://pokeapi.co/api/v2/pokemon/2/'},
  {'name': 'venusaur', 'url': 'https://pokeapi.co/api/v2/pokemon/3/'},
  {'name': 'charmander', 'url': 'https://pokeapi.co/api/v2/pokemon/4/'},
  {'name': 'charmeleon', 'url': 'https://pokeapi.co/api/v2/pokemon/5/'}]}

In [19]:
for pokemon in dados["results"]:
    print(pokemon["name"])

bulbasaur
ivysaur
venusaur
charmander
charmeleon

In [25]:
nome = input("Digite o nome de um pokémon: ").lower()
url = f"https://pokeapi.co/api/v2/pokemon/{nome}"

In [26]:
try:
    resposta = requests.get(url, timeout=10)
except requests.exceptions.RequestException:
    print("Não foi possível conectar à API")
    raise SystemExit

In [27]:
resposta

In [28]:
novo_post = {"title": "Meu primeiro post", "body": "Aprendendo APIs com Python", "userId": 1}
resposta = requests.post("https://jsonplaceholder.typicode.com/posts", json=novo_post)

In [29]:
print(resposta.status_code)
print(resposta.json())

201
{'title': 'Meu primeiro post', 'body': 'Aprendendo APIs com Python', 'userId': 1, 'id': 101}

## Bibliotecas importantes no Python

os, sys - como vc interage com o seu sistema operacional

datetime - datas e hora

re - Regex

In [31]:
import os
import sys

In [32]:
print(os.getcwd())

/Users/sthefanie/ciencia-de-dados/python-para-ciencia-de-dados

In [33]:
print(os.listdir())

['.DS_Store', 'uv.lock', 'arquivos_importantes', 'pyproject.toml', 'README.md', '.venv', 'material-teorico', 'python_testes.ipynb', '.python-version', 'src']

In [34]:
if not os.path.exists("relatorios"):
    os.mkdir("relatorios")

In [ ]:
meses = ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro']
caminho = os.path.join("relatorios", "janeiro.txt")
print(caminho)

relatorios/janeiro.txt

In [36]:
print(sys.version)

3.13.15 (main, Sep  1 2026, 14:05:45) [Clang 22.1.3 ]

In [37]:
print(sys.argv)

['/Users/sthefanie/ciencia-de-dados/python-para-ciencia-de-dados/.venv/lib/python3.13/site-packages/ipykernel_launcher.py', '--f=/Users/sthefanie/Library/Jupyter/runtime/kernel-v3a7b7b543c8f6d9826c0bc721bce1770e295510eb.json']

In [39]:
if len(sys.argv) < 2:
    print("Informe seu nome ao rodar o programa")
    sys.exit()

print(f"Olá, {sys.argv[1]}!")

Olá, --f=/Users/sthefanie/Library/Jupyter/runtime/kernel-v3a7b7b543c8f6d9826c0bc721bce1770e295510eb.json!

In [41]:
import datetime
print(datetime.datetime.now())

2026-10-04 09:29:26.573320

In [43]:
from datetime import datetime, timedelta

print(datetime.now())
print(datetime.now() + timedelta(days=7))

2026-10-04 09:30:13.227415
2026-10-11 09:30:13.227758

In [44]:
agora = datetime.now()
daqui_uma_semana = agora + timedelta(days=7)
print(daqui_uma_semana.strftime("%d/%m/%Y"))

11/10/2026

In [45]:
nascimento = datetime.strptime("30/11/1998", "%d/%m/%Y")
dias_vividos = (agora - nascimento).days
print(dias_vividos)

10170

In [46]:
countdown = datetime.strptime("30/11/2026", "%d/%m/%Y")
meu_aniversario = (countdown - agora).days
print(meu_aniversario)

56

In [47]:
# arquivo exemplo_re.py
import re

texto = "Meu telefone é 42 99999-1234 e o do trabalho é 42 3222-5678"
telefones = re.findall(r"\d{4,5}-\d{4}", texto)
print(telefones)

['99999-1234', '3222-5678']

In [50]:
email = "sthefanie@email.com"

if re.search(r"^\S+@\S+\.\S+$", email):
    print("E-mail válido")

E-mail válido

In [53]:
cpf = "123.456.789-00"
somente_numeros = re.sub(r"\D", "", cpf)
print(type(somente_numeros))

<class 'str'>

In [54]:
somente_numeros = int(somente_numeros)
print(type(somente_numeros))

<class 'int'>

## Bibliotecas de ciencia de dados

Numpy, Pandas e Matplotlib

In [57]:
## Numpy
import numpy as np

temperaturas = np.array([18, 21, 19, 25, 23, 17, 20])
print(temperaturas)
print(type(temperaturas))

[18 21 19 25 23 17 20]
<class 'numpy.ndarray'>

In [58]:
lista = [1, 2, 3]
print(lista + [10, 20, 30])

[1, 2, 3, 10, 20, 30]

In [59]:
array = np.array([1, 2, 3])
print(array + np.array([10, 20, 30]))

[11 22 33]

In [64]:
array = np.array([1, 2, 3])
print(array * np.array([10, 20, 30]))

[10 40 90]

In [65]:
fahrenheit = temperaturas * 9 / 5 + 32
print(fahrenheit)

[64.4 69.8 66.2 77.  73.4 62.6 68. ]

In [66]:
print(np.array([1, 2.5, 3]))

[1.  2.5 3. ]

In [68]:
print(fahrenheit[0])
print(fahrenheit[-1])
print(fahrenheit[1:4])

64.4
68.0
[69.8 66.2 77. ]

In [67]:
print(temperaturas[0])
print(temperaturas[-1])
print(temperaturas[1:4])

18
20
[21 19 25]

In [69]:
## estatisticas rapidas com numpy
print(temperaturas.mean()) # media
print(temperaturas.max()) # maximo
print(temperaturas.min()) # minimo
print(temperaturas.sum()) # soma
print(temperaturas.std()) # desvio padrao

20.428571428571427
25
17
143
2.610809554642438

In [70]:
print(temperaturas > 20)

[False  True False  True  True False False]

In [71]:
dias_quentes = temperaturas[temperaturas > 20]
print(dias_quentes)

[21 25 23]

In [73]:
notas = np.array([
    [7, 8, 6],
    [9, 5, 10]
])

print(notas.shape) # linhas e colunas
print(notas[0, 1]) # elemento na primeira linha e segunda coluna
print(notas[1, 2]) # elemento na segunda linha e terceira coluna

(2, 3)
8
10

In [74]:
print(notas.mean(axis=1)) # media por linha - média de cada aluno
print(notas.mean(axis=0)) # media por coluna - média de cada prova

[7. 8.]
[8.  6.5 8. ]

In [76]:
print(np.zeros(3))
print(np.arange(0, 11, 2))
print(np.linspace(0, 1, 5))

[0. 0. 0.]
[ 0  2  4  6  8 10]
[0.   0.25 0.5  0.75 1.  ]

In [77]:
print(np.linspace(0, 100, 5))

[  0.  25.  50.  75. 100.]

## Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
# series
# temperaturas = np.array([18, 21, 19, 25, 23, 17, 20])
temperaturas = pd.Series([18, 21, 19, 25, 23, 17, 20])
temperaturas

0    18
1    21
2    19
3    25
4    23
5    17
6    20
dtype: int64

In [3]:
dict_temperatura = {
    'Curitiba': [18, 21, 19, 25, 23, 17, 20],
    'Ponta Grossa': [20, 22, 21, 26, 24, 18, 19],
    'Londrina': [22, 24, 23, 27, 25, 19, 21]
}

list_temperatura = [[18, 20, 22],
 [21, 22, 24],
 [19, 21, 23],
 [25, 26, 27],
 [23, 24, 25],
 [17, 18, 19],
 [20, 19, 21]]

In [4]:
## dicionario em dataframe
df_dict = pd.DataFrame(dict_temperatura)
df_dict

   Curitiba  Ponta Grossa  Londrina
0        18            20        22
1        21            22        24
2        19            21        23
3        25            26        27
4        23            24        25
5        17            18        19
6        20            19        21

In [6]:
## lista para dataframe
df_list = pd.DataFrame(list_temperatura, columns=['Curitiba', 'Ponta Grossa', 'Londrina'])
df_list

   Curitiba  Ponta Grossa  Londrina
0        18            20        22
1        21            22        24
2        19            21        23
3        25            26        27
4        23            24        25
5        17            18        19
6        20            19        21

In [7]:
df_pessoas = pd.read_csv("arquivos_importantes/pessoas.csv")
df_pessoas

    nome  idade        cidade
0    Ana     28      Curitiba
1  Bruno     35  Ponta Grossa
2  Carla     22      Londrina
3  Diego     41      Curitiba
4  Elisa     30  Ponta Grossa

In [8]:
print(df_pessoas)

    nome  idade        cidade
0    Ana     28      Curitiba
1  Bruno     35  Ponta Grossa
2  Carla     22      Londrina
3  Diego     41      Curitiba
4  Elisa     30  Ponta Grossa

In [10]:
df_pessoas["cidade"]

0        Curitiba
1    Ponta Grossa
2        Londrina
3        Curitiba
4    Ponta Grossa
Name: cidade, dtype: str

In [11]:
df_pessoas["idade"]

0    28
1    35
2    22
3    41
4    30
Name: idade, dtype: int64

In [12]:
df_pessoas["nome"]

0      Ana
1    Bruno
2    Carla
3    Diego
4    Elisa
Name: nome, dtype: str

In [14]:
df_dict

   Curitiba  Ponta Grossa  Londrina
0        18            20        22
1        21            22        24
2        19            21        23
3        25            26        27
4        23            24        25
5        17            18        19
6        20            19        21

In [15]:
df_dict.head(3)

   Curitiba  Ponta Grossa  Londrina
0        18            20        22
1        21            22        24
2        19            21        23

In [17]:
df_dict.tail(3)

   Curitiba  Ponta Grossa  Londrina
4        23            24        25
5        17            18        19
6        20            19        21

In [18]:
df_dict.describe()

        Curitiba  Ponta Grossa   Londrina
count   7.000000      7.000000   7.000000
mean   20.428571     21.428571  23.000000
std     2.819997      2.819997   2.645751
min    17.000000     18.000000  19.000000
25%    18.500000     19.500000  21.500000
50%    20.000000     21.000000  23.000000
75%    22.000000     23.000000  24.500000
max    25.000000     26.000000  27.000000

In [19]:
df_pessoas.describe()

           idade
count   5.000000
mean   31.200000
std     7.190271
min    22.000000
25%    28.000000
50%    30.000000
75%    35.000000
max    41.000000

In [20]:
df_dict.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Curitiba      7 non-null      int64
 1   Ponta Grossa  7 non-null      int64
 2   Londrina      7 non-null      int64
dtypes: int64(3)
memory usage: 300.0 bytes

In [21]:
df_pessoas.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    5 non-null      str
 1   idade   5 non-null      int64
 2   cidade  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes