In [40]:
# bibliotecas
import pandas as pd
import numpy as np

In [41]:
df_unificado = pd.read_csv("../1.data/2.processed/dados_marco_abril.csv")
df_unificado.head()

,id_compra,score_1,score_2,score_3,score_4,score_5,score_6,pais,score_7,produto,...,score_8,score_9,score_10,data_compra,valor_compra,score_fraude_modelo,fraude,entrega_doc_1,entrega_doc_2,entrega_doc_3
0,1,4,0.7685,94436.24,20.0,0.444828,1.0,BR,5,Máquininha Corta Barba Cabelo Peito Perna Pelo...,...,0.883598,240.0,102.0,2020-03-27 11:51:16,5.64,66,0,1,NaN,N
1,3,4,0.7455,242549.09,3.0,0.000000,19.0,AR,23,Bicicleta Mountain Fire Bird Rodado 29 Alumini...,...,0.516368,1779.0,77.0,2020-03-25 18:13:38,339.32,95,0,1,NaN,N
2,7,4,0.5962,7121.78,2.0,0.398000,0.0,BR,11,"Corpinho Avulso Joseph, Josepha Ou Placa Sem Sexo",...,0.204991,127.0,125.0,2020-03-22 19:20:24,10.56,71,0,0,NaN,N
3,10,4,0.4759,40143.12,50.0,0.000000,41.0,AR,3,Gamepad Joystick Para Telefono Celular Android...,...,0.735790,4701.0,940.0,2020-03-11 15:06:38,30.48,60,0,1,NaN,Y
4,11,4,0.8353,121926.06,39.0,0.186957,34.0,BR,24,Escova Dental Curaprox 5460 Ultra Soft Com 3 U...,...,0.943792,3248.0,132.0,2020-03-15 19:18:50,14.85,10,0,1,Y,Y

In [42]:
df_unificado.info()

<class 'pandas.DataFrame'>
RangeIndex: 150250 entries, 0 to 150249
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_compra            150250 non-null  int64
 1   score_1              150250 non-null  int64
 2   score_2              137265 non-null  float64
 3   score_3              137265 non-null  float64
 4   score_4              149884 non-null  float64
 5   score_5              150250 non-null  float64
 6   score_6              150239 non-null  float64
 7   pais                 150054 non-null  str
 8   score_7              150250 non-null  int64
 9   produto              150250 non-null  str
 10  categoria_produto    150250 non-null  str
 11  score_8              150250 non-null  float64
 12  score_9              150239 non-null  float64
 13  score_10             149884 non-null  float64
 14  data_compra          150250 non-null  str
 15  valor_compra         150250 non-null  float64
 16  score_fraude_modelo  150250 non-null  int64
 17  fraude               150250 non-null  int64
 18  entrega_doc_1        150250 non-null  int64
 19  entrega_doc_2        41212 non-null   str
 20  entrega_doc_3        150250 non-null  str
dtypes: float64(9), int64(6), str(6)
memory usage: 24.1 MB

## tratamento de inconsistencias 

coluna `data_compra` para datetime

ver se existem linhas duplicadas

ver sobre os valores nulos

quantas fraudes tem no dataset

In [43]:
df_unificado['data_compra'].head()

0    2020-03-27 11:51:16
1    2020-03-25 18:13:38
2    2020-03-22 19:20:24
3    2020-03-11 15:06:38
4    2020-03-15 19:18:50
Name: data_compra, dtype: str

In [44]:
df_unificado['data_compra'] = pd.to_datetime(df_unificado['data_compra'])
print(df_unificado['data_compra'].dtype)
df_unificado['data_compra'].head()

datetime64[us]

0   2020-03-27 11:51:16
1   2020-03-25 18:13:38
2   2020-03-22 19:20:24
3   2020-03-11 15:06:38
4   2020-03-15 19:18:50
Name: data_compra, dtype: datetime64[us]

In [45]:
## linhas duplicadas
df_unificado.duplicated().sum()

np.int64(250)

In [46]:
linhas_duplicadas = df_unificado[df_unificado.duplicated()]
linhas_duplicadas

,id_compra,score_1,score_2,score_3,score_4,score_5,score_6,pais,score_7,produto,...,score_8,score_9,score_10,data_compra,valor_compra,score_fraude_modelo,fraude,entrega_doc_1,entrega_doc_2,entrega_doc_3
78453,64219,4,1.0000,535.08,50.0,0.259026,4.0,BR,1,Alavanca Full Auto #38 We M92 Samurai Edge,...,0.572792,2138.0,452.0,2020-04-12 21:17:45,18.87,40,0,1,NaN,Y
78839,121664,4,0.8129,37474.43,50.0,0.000000,13.0,BR,10,Coelho Sansão Pelúcia 50cm Turma Da Mônica Ori...,...,0.229014,3862.0,996.0,2020-04-03 07:41:50,31.95,24,0,1,NaN,Y
78892,3204,4,0.7794,43342.44,50.0,1.331104,86.0,BR,29,Organizador Porta Comprimidos E Remédios - 7 D...,...,0.184518,2133.0,764.0,2020-04-07 21:07:14,2.90,7,0,1,NaN,Y
79353,124754,2,0.5157,32489.48,5.0,0.000000,108.0,AR,32,Riel 2mts Para Mensula Doble Reforzado Todoest...,...,0.486794,5809.0,143.0,2020-04-21 20:18:09,37.63,6,0,1,NaN,Y
79904,10437,4,0.7660,64396.62,50.0,0.089634,29.0,BR,24,Kit 10 Mini Spot Embutir Led Redondo 3w Branco...,...,0.546726,2907.0,438.0,2020-04-18 20:03:43,15.16,47,0,1,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148752,120814,4,0.5727,29145.32,1.0,0.247198,2.0,AR,15,Muñeco Transformer Simil Optimus Prime Bumbleb...,...,0.768834,745.0,0.0,2020-04-08 12:17:01,26.35,30,0,1,NaN,N
148919,126985,4,0.7288,186213.43,34.0,0.406953,1.0,BR,30,Lente Retrovisor Hb20 2012 2013 2014 2015 16 1...,...,0.289483,777.0,116.0,2020-04-20 19:45:43,9.44,47,0,1,NaN,Y
149051,13954,4,0.7735,118454.38,50.0,0.141068,28.0,BR,6,Arranjo Noah Orquídea Toque Real - Decoração P...,...,0.968042,2660.0,715.0,2020-04-21 15:02:39,23.12,70,0,1,NaN,Y
149078,48127,4,0.6380,167793.89,1.0,0.304539,8.0,BR,42,Toner Tn2340 Para Dcp-l2520 L2520d L2520dw Dcp...,...,0.428939,1548.0,0.0,2020-04-06 20:57:56,10.22,30,0,1,NaN,N
149128,95629,4,0.7884,44415.18,1.0,0.161848,0.0,BR,7,Blazer Feminino Longo Acinturado Maxxi Sem For...,...,0.509057,2590.0,0.0,2020-04-02 16:15:42,10.84,82,0,1,Y,N

In [47]:
df_unificado[df_unificado.duplicated(keep=False)].value_counts().reset_index(name='qtd')

,id_compra,score_1,score_2,score_3,score_4,score_5,score_6,pais,score_7,produto,...,score_9,score_10,data_compra,valor_compra,score_fraude_modelo,fraude,entrega_doc_1,entrega_doc_2,entrega_doc_3,qtd
0,8972,4,0.5897,26755.88,2.0,0.000000,4.0,AR,1,Fuente Switching 12v Led Camaras Metalica 5a 6...,...,203.0,203.0,2020-04-09 18:34:37,51.61,68,0,1,N,Y,2
1,129795,4,0.8240,1013530.22,50.0,0.000000,5.0,BR,28,Kit Embreagem Siena 1.0 Mpi 8v Fire 2012 2013 ...,...,1031.0,627.0,2020-04-15 10:48:24,47.88,3,0,1,Y,Y,2
2,135084,4,0.6169,117143.46,50.0,0.645770,351.0,US,32,Cable Red Largo Utp 20 Metros Cat 5e Patchcord...,...,2183.0,608.0,2020-04-06 14:54:58,7.81,22,0,1,Y,Y,2
3,221,4,0.6667,72794.75,50.0,0.259766,14.0,BR,5,Capinha Fibra Anti Impact Moto E6 Plus + Pelic...,...,2497.0,847.0,2020-04-20 18:44:35,9.58,64,0,1,Y,Y,2
4,10062,4,0.7830,23773.41,50.0,0.000000,2.0,BR,31,Colunax Aliviador Kit Com 60 Unidades 60ml - P...,...,469.0,466.0,2020-04-21 08:23:29,67.52,4,0,1,Y,Y,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,92905,4,0.7835,116067.00,1.0,0.000000,0.0,BR,6,"Relógio Smarwatch ,bluetooth ,ligações,chip+fo...",...,5.0,5.0,2020-04-04 12:01:17,39.11,92,1,0,N,N,2
63,94703,2,0.6482,99.93,3.0,0.000000,147.0,AR,1,Desmalezadora Motoguadaña Bordeadora Niwa 52cc,...,5425.0,46.0,2020-04-16 13:43:54,115.10,16,0,1,Y,N,2
64,84334,4,0.8435,37188.13,50.0,0.228378,0.0,BR,37,10 Fronhas Malha Berço Travesseiro Bebê 30x40 ...,...,4740.0,1062.0,2020-04-18 02:38:49,14.57,69,0,1,Y,Y,2
65,97763,4,0.7060,33328.49,3.0,0.073071,31.0,AR,41,Old Prince Cordero Y Arroz 15 Kg Dermadefense ...,...,3917.0,270.0,2020-04-08 11:03:40,35.66,87,0,1,Y,Y,2
66,148717,4,0.7993,186984.91,3.0,0.000000,9.0,BR,12,Jogo Calota Ds4 Preta Cromada Aro 15 Gm Cobalt...,...,1158.0,112.0,2020-04-09 12:50:20,39.69,58,0,1,N,Y,2

In [48]:
df_unificado = df_unificado.drop_duplicates(keep='first').reset_index(drop=True)
df_unificado.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_compra            150000 non-null  int64
 1   score_1              150000 non-null  int64
 2   score_2              137016 non-null  float64
 3   score_3              137016 non-null  float64
 4   score_4              149635 non-null  float64
 5   score_5              150000 non-null  float64
 6   score_6              149989 non-null  float64
 7   pais                 149806 non-null  str
 8   score_7              150000 non-null  int64
 9   produto              150000 non-null  str
 10  categoria_produto    150000 non-null  str
 11  score_8              150000 non-null  float64
 12  score_9              149989 non-null  float64
 13  score_10             149635 non-null  float64
 14  data_compra          150000 non-null  datetime64[us]
 15  valor_compra         150000 non-null  float64
 16  score_fraude_modelo  150000 non-null  int64
 17  fraude               150000 non-null  int64
 18  entrega_doc_1        150000 non-null  int64
 19  entrega_doc_2        41143 non-null   str
 20  entrega_doc_3        150000 non-null  str
dtypes: datetime64[us](1), float64(9), int64(6), str(5)
memory usage: 24.0 MB

### Verificação dos valores nulos

In [49]:
df_unificado.isna().sum()

id_compra                   0
score_1                     0
score_2                 12984
score_3                 12984
score_4                   365
score_5                     0
score_6                    11
pais                      194
score_7                     0
produto                     0
categoria_produto           0
score_8                     0
score_9                    11
score_10                  365
data_compra                 0
valor_compra                0
score_fraude_modelo         0
fraude                      0
entrega_doc_1               0
entrega_doc_2          108857
entrega_doc_3               0
dtype: int64

In [50]:
df_unificado.head()

,id_compra,score_1,score_2,score_3,score_4,score_5,score_6,pais,score_7,produto,...,score_8,score_9,score_10,data_compra,valor_compra,score_fraude_modelo,fraude,entrega_doc_1,entrega_doc_2,entrega_doc_3
0,1,4,0.7685,94436.24,20.0,0.444828,1.0,BR,5,Máquininha Corta Barba Cabelo Peito Perna Pelo...,...,0.883598,240.0,102.0,2020-03-27 11:51:16,5.64,66,0,1,NaN,N
1,3,4,0.7455,242549.09,3.0,0.000000,19.0,AR,23,Bicicleta Mountain Fire Bird Rodado 29 Alumini...,...,0.516368,1779.0,77.0,2020-03-25 18:13:38,339.32,95,0,1,NaN,N
2,7,4,0.5962,7121.78,2.0,0.398000,0.0,BR,11,"Corpinho Avulso Joseph, Josepha Ou Placa Sem Sexo",...,0.204991,127.0,125.0,2020-03-22 19:20:24,10.56,71,0,0,NaN,N
3,10,4,0.4759,40143.12,50.0,0.000000,41.0,AR,3,Gamepad Joystick Para Telefono Celular Android...,...,0.735790,4701.0,940.0,2020-03-11 15:06:38,30.48,60,0,1,NaN,Y
4,11,4,0.8353,121926.06,39.0,0.186957,34.0,BR,24,Escova Dental Curaprox 5460 Ultra Soft Com 3 U...,...,0.943792,3248.0,132.0,2020-03-15 19:18:50,14.85,10,0,1,Y,Y

In [51]:
df_unificado['entrega_doc_2'].value_counts() # contagem dos valores únicos da coluna 'entrega_doc_2'

entrega_doc_2
Y    24091
N    17052
Name: count, dtype: int64

In [52]:
df_unificado['entrega_doc_2'].unique()

<StringArray>
[nan, 'Y', 'N']
Length: 3, dtype: str

In [53]:
df_unificado['pais'].value_counts()

pais
BR    111628
AR     31964
UY      2967
US      2273
SE       358
MX       236
RU        73
ES        69
CO        64
GB        43
FR        18
IT        14
PT        13
DE         9
CL         9
PE         5
EC         4
PY         4
AU         3
CA         3
CH         3
CN         3
NZ         3
UA         3
BE         3
PA         3
BO         2
CR         2
NL         2
PR         2
AE         2
LB         2
KR         1
NI         1
IN         1
TR         1
DO         1
EG         1
TW         1
JP         1
ZA         1
GR         1
GE         1
AD         1
BS         1
IL         1
FI         1
HN         1
PH         1
GH         1
NO         1
Name: count, dtype: int64

In [54]:
df_unificado['pais'].unique()

<StringArray>
['BR', 'AR', 'GB', 'UY', 'US', 'MX', 'SE', 'RU',  nan, 'AU', 'ES', 'PT', 'IT',
 'CO', 'CA', 'EC', 'DE', 'KR', 'FR', 'NI', 'CH', 'IN', 'BO', 'CL', 'CN', 'PE',
 'TR', 'DO', 'EG', 'NZ', 'UA', 'CR', 'BE', 'TW', 'PA', 'JP', 'ZA', 'GR', 'PY',
 'NL', 'GE', 'AD', 'BS', 'IL', 'PR', 'AE', 'FI', 'LB', 'HN', 'PH', 'GH', 'NO']
Length: 52, dtype: str

Possibilidades do que fazer com os dados nulos (`.isna()` ou `.isnull()` e fazendo um `.sum()`), no geral:
1. Remover os dados;
2. Preencher os numéricos com: média, mediana, 999 ou -999
3. Para preencher booleanos: se aquele dado não existe, ver se faz sentido, colocar ele como um "não"/0
4. Para preencher textos: "Desconhecido", "Não informado"


O que escolhemos fazer nos nosso dados.
- `entrega_doc_2`: nós podemos optar em colocar como `'N'`
- valores das colunas de `score`:  nesse momento, podemos optar pela mediana
- `pais`: podemos colocar como `Desconhecido`

In [55]:
## exemplo de média e mediana com array numpy
array = np.array([1, 0, 9, 0, 5, 10, 7, 0, 10, 10])
print(f'Média: {np.mean(array)}')
print(f'Mediana: {np.median(array)}')

Média: 5.2
Mediana: 6.0

In [56]:
df_unificado['pais'] = df_unificado['pais'].fillna('Desconhecido')
print(df_unificado['pais'].isna().sum())
print(df_unificado['pais'].value_counts())

0
pais
BR              111628
AR               31964
UY                2967
US                2273
SE                 358
MX                 236
Desconhecido       194
RU                  73
ES                  69
CO                  64
GB                  43
FR                  18
IT                  14
PT                  13
DE                   9
CL                   9
PE                   5
EC                   4
PY                   4
AU                   3
CA                   3
CH                   3
CN                   3
NZ                   3
UA                   3
BE                   3
PA                   3
BO                   2
CR                   2
NL                   2
PR                   2
AE                   2
LB                   2
KR                   1
NI                   1
IN                   1
TR                   1
DO                   1
EG                   1
TW                   1
JP                   1
ZA                   1
GR                   1
GE                   1
AD                   1
BS                   1
IL                   1
FI                   1
HN                   1
PH                   1
GH                   1
NO                   1
Name: count, dtype: int64

In [57]:
## com o nosso entrega_doc_2
df_unificado['entrega_doc_2'] = df_unificado['entrega_doc_2'].fillna('N')
print(df_unificado['entrega_doc_2'].isna().sum())
print(df_unificado['entrega_doc_2'].value_counts())

0
entrega_doc_2
N    125909
Y     24091
Name: count, dtype: int64

In [58]:
df_unificado.isna().sum()

id_compra                  0
score_1                    0
score_2                12984
score_3                12984
score_4                  365
score_5                    0
score_6                   11
pais                       0
score_7                    0
produto                    0
categoria_produto          0
score_8                    0
score_9                   11
score_10                 365
data_compra                0
valor_compra               0
score_fraude_modelo        0
fraude                     0
entrega_doc_1              0
entrega_doc_2              0
entrega_doc_3              0
dtype: int64

In [59]:
scores_nulos = ['score_2', 'score_3', 'score_4', 'score_6', 'score_9', 'score_10']

for score in scores_nulos:
    ##mediana para preencher os valores nulos
    mediana = df_unificado[score].median()
    df_unificado[score] = df_unificado[score].fillna(mediana)
    
    print(df_unificado[score].isna().sum())

0
0
0
0
0
0

In [60]:
df_unificado.isna().sum()

id_compra              0
score_1                0
score_2                0
score_3                0
score_4                0
score_5                0
score_6                0
pais                   0
score_7                0
produto                0
categoria_produto      0
score_8                0
score_9                0
score_10               0
data_compra            0
valor_compra           0
score_fraude_modelo    0
fraude                 0
entrega_doc_1          0
entrega_doc_2          0
entrega_doc_3          0
dtype: int64

### Manipulação dos documentos 
'N' -> 0

'Y' -> 1

In [61]:
print(df_unificado['entrega_doc_1'].value_counts())
print(df_unificado['entrega_doc_2'].value_counts())
print(df_unificado['entrega_doc_3'].value_counts())

entrega_doc_1
1    135353
0     14647
Name: count, dtype: int64
entrega_doc_2
N    125909
Y     24091
Name: count, dtype: int64
entrega_doc_3
Y    83129
N    66871
Name: count, dtype: int64

In [62]:
sim_nao = {'Y': 1, 'N': 0}
df_unificado['entrega_doc_2'] = df_unificado['entrega_doc_2'].map(sim_nao)
df_unificado['entrega_doc_3'] = df_unificado['entrega_doc_3'].map(sim_nao)

print(df_unificado['entrega_doc_1'].value_counts())
print(df_unificado['entrega_doc_2'].value_counts())
print(df_unificado['entrega_doc_3'].value_counts())

entrega_doc_1
1    135353
0     14647
Name: count, dtype: int64
entrega_doc_2
0    125909
1     24091
Name: count, dtype: int64
entrega_doc_3
1    83129
0    66871
Name: count, dtype: int64

## Fraudes em países

In [63]:
df_unificado['pais'].value_counts().head(10)

pais
BR              111628
AR               31964
UY                2967
US                2273
SE                 358
MX                 236
Desconhecido       194
RU                  73
ES                  69
CO                  64
Name: count, dtype: int64

#### sobre a regra do nosso agrupamento

>pensamentos futuros


>países que tem mais de 10 mil dados, podemos deixar eles por eles mesmos. 
>se eles tem menos de 10 mil, podemos agrupar com outros países.

BR e AR ficam e o resto é colocado como um único agrupamento.

In [64]:
def agrupar_paises(pais):
    if pais in ["BR", "AR"]: # a nossa lógica de deixar os países 
        return pais
    else:
        return "Outros"

In [65]:
## .apply() para aplicar a função agrupar_paises em cada elemento da coluna 'pais'
# .apply() é feito em uma coluna, por isso o ponto, e dentro dos () dele passamos a função que vamos aplicar.
df_unificado['pais_agrupado'] = df_unificado['pais'].apply(agrupar_paises)
df_unificado['pais_agrupado'].value_counts()

pais_agrupado
BR        111628
AR         31964
Outros      6408
Name: count, dtype: int64

### lambda - 

é uma função que é usada pontualmente e geralmente é curta

transformando a nossa função `agrupar_paises` em uma função lambda:
```
def agrupar_paises(pais):
    if pais in ["BR", "AR"]: # a nossa lógica de deixar os países 
        return pais
    else:
        return "Outros"
```

```
lambda pais: pais if pais in ["BR", "AR"] else "Outros"
```

- `def agrupar_paises(pais):` vira `lambda pais:`
- `if pais in ["BR", "AR"]: return pais` vira `pais if pais in ["BR", "AR"]`
- `else: return "Outros"` vira `else "Outros"`

In [66]:
## criando as colunas de hora_compra e dia_semana
df_unificado['data_compra'].dtype

dtype('<M8[us]')

In [67]:
dias_semana_dict = {'0': 'Segunda', 
                    '1': 'Terça', 
                    '2': 'Quarta', 
                    '3': 'Quinta', 
                    '4': 'Sexta', 
                    '5': 'Sábado',
                    '6': 'Domingo'}

In [68]:
df_unificado['dia_semana'] = df_unificado['data_compra'].dt.dayofweek.astype(str).map(dias_semana_dict)
# .dt.dayofweek retorna de 0 a 6, sendo o 0 a segunda feira e 6 o domingo

In [69]:
df_unificado['dia_semana'].unique()

<StringArray>
['Sexta', 'Quarta', 'Domingo', 'Segunda', 'Sábado', 'Quinta', 'Terça']
Length: 7, dtype: str

In [70]:
df_unificado['hora_compra'] = df_unificado['data_compra'].dt.strftime("%H:%M")
df_unificado['hora_compra'].head()

0    11:51
1    18:13
2    19:20
3    15:06
4    19:18
Name: hora_compra, dtype: str

In [71]:
df_unificado.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_compra            150000 non-null  int64
 1   score_1              150000 non-null  int64
 2   score_2              150000 non-null  float64
 3   score_3              150000 non-null  float64
 4   score_4              150000 non-null  float64
 5   score_5              150000 non-null  float64
 6   score_6              150000 non-null  float64
 7   pais                 150000 non-null  str
 8   score_7              150000 non-null  int64
 9   produto              150000 non-null  str
 10  categoria_produto    150000 non-null  str
 11  score_8              150000 non-null  float64
 12  score_9              150000 non-null  float64
 13  score_10             150000 non-null  float64
 14  data_compra          150000 non-null  datetime64[us]
 15  valor_compra         150000 non-null  float64
 16  score_fraude_modelo  150000 non-null  int64
 17  fraude               150000 non-null  int64
 18  entrega_doc_1        150000 non-null  int64
 19  entrega_doc_2        150000 non-null  int64
 20  entrega_doc_3        150000 non-null  int64
 21  pais_agrupado        150000 non-null  str
 22  dia_semana           150000 non-null  str
 23  hora_compra          150000 non-null  str
dtypes: datetime64[us](1), float64(9), int64(8), str(6)
memory usage: 27.5 MB

In [72]:
df_unificado.columns

Index(['id_compra', 'score_1', 'score_2', 'score_3', 'score_4', 'score_5',
       'score_6', 'pais', 'score_7', 'produto', 'categoria_produto', 'score_8',
       'score_9', 'score_10', 'data_compra', 'valor_compra',
       'score_fraude_modelo', 'fraude', 'entrega_doc_1', 'entrega_doc_2',
       'entrega_doc_3', 'pais_agrupado', 'dia_semana', 'hora_compra'],
      dtype='str')

### Separar as bases de dados

uma base de informações da compra : dados_compras

uma base de informações dos scores de cada compra: fraudes_scores

In [73]:
colunas_compras = ['id_compra', 'produto', 'categoria_produto',  'valor_compra', 
                   'data_compra', 'dia_semana', 'hora_compra', 'pais',  'pais_agrupado',
                   'entrega_doc_1', 'entrega_doc_2', 'entrega_doc_3', 'fraude']

colunas_scores = ['id_compra', 'score_1', 'score_2', 'score_3', 'score_4',
                  'score_5','score_6', 'score_7', 'score_8', 'score_9', 
                  'score_10', 'score_fraude_modelo', 'fraude']

In [76]:
for coluna in df_unificado.columns:
    if coluna in colunas_compras and coluna not in colunas_scores:
        print(coluna)

pais
produto
categoria_produto
data_compra
valor_compra
entrega_doc_1
entrega_doc_2
entrega_doc_3
pais_agrupado
dia_semana
hora_compra

In [78]:
dados_compras = df_unificado[colunas_compras]
print(dados_compras.shape)
dados_compras.head()

(150000, 13)

,id_compra,produto,categoria_produto,valor_compra,data_compra,dia_semana,hora_compra,pais,pais_agrupado,entrega_doc_1,entrega_doc_2,entrega_doc_3,fraude
0,1,Máquininha Corta Barba Cabelo Peito Perna Pelo...,cat_8d714cd,5.64,2020-03-27 11:51:16,Sexta,11:51,BR,BR,1,0,0,0
1,3,Bicicleta Mountain Fire Bird Rodado 29 Alumini...,cat_e9110c5,339.32,2020-03-25 18:13:38,Quarta,18:13,AR,AR,1,0,0,0
2,7,"Corpinho Avulso Joseph, Josepha Ou Placa Sem Sexo",cat_5d6059e,10.56,2020-03-22 19:20:24,Domingo,19:20,BR,BR,0,0,0,0
3,10,Gamepad Joystick Para Telefono Celular Android...,cat_5d79fb9,30.48,2020-03-11 15:06:38,Quarta,15:06,AR,AR,1,0,1,0
4,11,Escova Dental Curaprox 5460 Ultra Soft Com 3 U...,cat_4744ece,14.85,2020-03-15 19:18:50,Domingo,19:18,BR,BR,1,1,1,0

In [79]:
fraudes_scores = df_unificado[colunas_scores]
print(fraudes_scores.shape)
fraudes_scores.head()

(150000, 13)

,id_compra,score_1,score_2,score_3,score_4,score_5,score_6,score_7,score_8,score_9,score_10,score_fraude_modelo,fraude
0,1,4,0.7685,94436.24,20.0,0.444828,1.0,5,0.883598,240.0,102.0,66,0
1,3,4,0.7455,242549.09,3.0,0.000000,19.0,23,0.516368,1779.0,77.0,95,0
2,7,4,0.5962,7121.78,2.0,0.398000,0.0,11,0.204991,127.0,125.0,71,0
3,10,4,0.4759,40143.12,50.0,0.000000,41.0,3,0.735790,4701.0,940.0,60,0
4,11,4,0.8353,121926.06,39.0,0.186957,34.0,24,0.943792,3248.0,132.0,10,0

In [80]:
dados_compras.to_csv("../1.data/2.processed/dados_compras.csv", index=False)
fraudes_scores.to_csv("../1.data/2.processed/fraudes_scores.csv", index=False)